Complete project based on template.
EasyMicroservices/Storage-Microservice pull request #4
Opened 2023-07-17 13:44 UTC by MahdiyarGHD

2023-07-17 20:05 UTC, Ali-YousefiTelori requested changes

2023-07-17 20:05 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Database/Database/Entities/FileEntity.cs
> +        public string Guid { get; set; }
Change this type to System.Guid

2023-07-17 20:05 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Common/ResultContract.cs
> +        public object OutputRes { get; set; }
Do not use the object in contract, use real type

2023-07-17 20:05 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Common/ResultContract.cs
> +        public int StatusId { get; set; }
Use Status as Enum and change its name to Status

2023-07-17 20:05 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Requests/FileRequest.cs
Add Contract suffix end of all contracts, it must be FileRequestContract

2023-07-17 20:05 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Requests/FolderRequest.cs
Add Contract suffix end of all contracts, it must be FolderRequestContract

2023-07-17 20:05 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Requests/FolderRequest.cs
> +    public class AddFolderDom
Dont use the 'Dom' suffix, only Contract is good.
move it to requests.
rename it to AddFolderRequestContract

2023-07-17 20:05 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Requests/FolderRequest.cs
> +    public class UpdateFolderDom
Don't use the 'Dom' suffix, only Contract is good.
move it to requests.
rename it to AddFolderRequestContract

2023-07-18 09:37 UTC, mahdidelzendeh72 approved these changes

2023-07-18 13:24 UTC, Ali-YousefiTelori requested changes

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.WebApi/Controllers/FileController.cs
> +        public async Task<MessageContract<object>> AddSingleFileAsync([FromForm] AddFileContract input)
Don't use object in reesult or any request

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.WebApi/Controllers/FileController.cs
> +        public async Task<MessageContract<FileEntity>> DeleteFileByGuidAsync(string guid, string? password)
Don't send entities as result, only use contracts.

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.WebApi/Controllers/FileController.cs
> +        public async Task<MessageContract<FileEntity>> DeleteFileByIdAsync(long id, string? password)
don't use entities as a result only sned contracts

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.WebApi/Controllers/FolderController.cs
> +        public async Task<MessageContract<List<FolderEntity>>> GetAll()
Dont use entities as service results

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.WebApi/Controllers/FolderController.cs
> +        public async Task<MessageContract<FolderEntity>> UpdateAsync(UpdateFolderContract input)
Dont use entities as service results

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.WebApi/Controllers/FolderController.cs
> +        public async Task<MessageContract<FolderEntity>> AddAsync(AddFolderContract input)
Dont use entities as service results

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.WebApi/Controllers/FolderController.cs
> +        public async Task<MessageContract> DeleteAsync(long Id)
rename Id = fileId, don't use pascal case as parameter names

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Requests/FolderRequestContract.cs
File name and class name are not same

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Requests/FolderRequestContract.cs
> +    public class UpdateFolderContract
don't add two class in one file

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Requests/FileRequestContract.cs
File name and class name are not same

2023-07-18 13:24 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Common/ResultContract.cs
Remove this file and statuses,
MessageContract has FailedReasonType

2023-07-18 16:02 UTC, mahdidelzendeh72 approved these changes

2023-07-18 16:28 UTC, MahdiyarGHD commented on src/CSharp/EasyMicroservices.StorageMicroservice.Domain/Contracts/Requests/FolderRequestContract.cs
Just to clarify, my initial plan was to consolidate all necessary contracts for each project section into a single contract file. However, I've made the requested changes

2023-07-18 18:50 UTC, Ali-YousefiTelori approved these changes

2023-07-18 18:50 UTC, merged